### ISSUE TITLE
The app store page for downloading the new version does not open downloading

### ISSUE THREAD

**Issue by furiosFast** [rwbutler/Updates#1]
**Describe the bug**
The app store page for downloading the new version does not open
downloading

**To Reproduce**
Watch the attached video

**Screenshots**
Video link: https://streamable.com/cywpy

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**
 - Device: iPhone X
 - OS: iOS 12.1.4

**Comment by rwbutler** [comment]
Sorry for the delay looking into this one - I've been away on holiday - I'll look into what's gone wrong here.

**Comment by rwbutler** [comment]
It looks as though store information is not being loaded for your particular app. Would you be able to run the following code and let me know what gets printed for you app?

```swift        
Updates.checkForUpdates { result in
            print(Updates.bundleIdentifier)
            print(Updates.countryCode)
            print(Updates.appStoreId)
            print(Updates.appStoreURL)
        }
```

**Comment by rwbutler** [comment]
Because a bit of time has passed now, I'm going to close this issue for now but if you manage to find any further information let me know and we can re-open this.
