### ISSUE TITLE
Option to make the update required or not

### ISSUE THREAD

**Issue by zeusent** [rwbutler/Updates#11]
**Is your feature request related to a problem? Please describe.**
When a new version of the app is available we can use this framework to show a message to our users that they should update. But this message can be dismissed and have the users continue the normal flow in the old app.

**Describe the solution you'd like**
It would be awesome if the JSON config file could specify a minimum required version that the users should have installed on their devices for the continue action to be shown.

**Additional context**
Imagine an app is at version `1.0.0` and version `1.1.0` is released. The users get the "a new version" is available message which they can decide to ignore by pressing "Ok" or not by pressing "Update".

It would be nice that if we could say that users may not dismiss the update message if they are running on any version lower than `1.1.0`

**Comment by BhavikThummar** [comment]
@zeusent Did you find any solution?

**Comment by rwbutler** [comment]
Hi @zeusent @BhavikThummar this exists now, please see: https://github.com/rwbutler/Updates/issues/20 thanks!
