### ISSUE TITLE
MacOS support?

### ISSUE THREAD

**Issue by philipyoungg** [rwbutler/Updates#15]
just curious: how hard it is to make this library support macos app store version?

From quick look at the code base, would changing the app store url with flag works? 

Then the alert UI could be called depending on OS from the custom flag.

**Comment by rwbutler** [comment]
@anmolrajpal How do you integrate? Through SPM? I'll take a look to see if the UIKit code can be moved into a separate target. Happy to accept PRs if you're able to look at this faster?

**Comment by rwbutler** [comment]
@anmolrajpal @philipyoungg If you integrate 2.0.0 using SPM I've excluded the UIKit code from the target. Let me know how you get on.
