### ISSUE TITLE
cant open app store on iOS 12

### ISSUE THREAD

**Issue by shayneoneill** [rwbutler/Updates#2]
**Describe the bug**
Appstore link opens in a window then autocloses before it can be interacted with on ios 12

**To Reproduce**

        Updates.checkForUpdates { result in
            //UpdatesUI.promptToUpdate(result, presentingViewController: viewCtl)
            UpdatesUI.promptToUpdate(result,
                                     animated: true,
                                     completion: {
                              print ("All done")
            }, presentingViewController: viewCtl)
        }

(I've tried it with the result/presentingviewcontroller overloading too. same result)

**Expected behavior**
I would expect to be taken to the app store?

**Screenshots**

![IMG_EF7B316C8460-1](https://user-images.githubusercontent.com/496071/66105743-d6c93b00-e5ee-11e9-8e8e-45ff99e4b986.jpeg)

**Smartphone (please complete the following information):**
 - Device: iPhone 8
 - OS: IOS 12

**Comment by shayneoneill** [comment]
Updated. Pans out this is on IOS 12. Now I'm double confused by it :/

**Comment by rwbutler** [comment]
Thanks for reporting this - I'll take a look.

**Comment by rwbutler** [comment]
I've just pushed v1.1.1 with a fix which I'm hoping should resolve this for you 👍🏻

**Comment by shayneoneill** [comment]
I'm going to delete my screenshot. That probably should be in public :/
