### ISSUE TITLE
Always Shows Update Available Duplicate "v"

### ISSUE THREAD

**Issue by willm132** [rwbutler/Updates#26]
Current Version -> is 2.1.1
Shows Update Available -> vv2.1.1

<img width="266" alt="Screenshot 2024-01-15 at 2 02 22 PM" src="https://github.com/rwbutler/Updates/assets/47162632/d0a9204f-e320-468a-87ab-ad3c68ca9d93">

**Comment by rwbutler** [comment]
Should be resolved in [2.0.1](https://github.com/rwbutler/Updates/releases/tag/2.0.1) - let me know how you get on.
