### ISSUE TITLE
Describing use of required reason API

### ISSUE THREAD

**Issue by hsingh-texada** [rwbutler/Updates#27]
Starting spring of 2024, Apple will be mandating the use of xcprivacy file to be included by all the libraries.
The relevant Apple requirement/documentation is as follows:
https://developer.apple.com/documentation/bundleresources/privacy_manifest_files/describing_use_of_required_reason_api

Can you please provide timelines on when this would be resolved, as it will directly impact our AppStore submissions.

**Comment by rwbutler** [comment]
@hsingh-texada Should be available now in 2.0.0 - let me know how you get on with this.
