### ISSUE TITLE
alert for higher version

### ISSUE THREAD

**Issue by mriccasyncpoint** [rwbutler/Updates#5]
Hello,
unfortunately I just brought a new version of the app on the app store, with version 1.7.0.
Once the app is installed, the alert for the previous version 1.6.3 releases.
Can a check be placed inside the code that causes the alert to exit only if the installed version is "<" of the installed version?

**Comment by rwbutler** [comment]
Apologies, I don't think I've quite understood the question - is it that after Updates has presented the App Store and allowed the user to download version 1.7.0 of your app from within version 1.6.3 of your app then the alert is presented again?

**Comment by rwbutler** [comment]
Thanks for letting me know about this - I've released a fix (v1.2.2). Hopefully this should resolve the issue for you.
