### ISSUE TITLE
False alarm because of wrong version comparision

### ISSUE THREAD

**Issue by broncha** [rwbutler/Updates#6]
```
Updates.updateAvailable(appVersion: "1.5.0", apiVersion: "1.4.4", comparator: .patch))
```

This returns `true` which is wrong. The app version from api is 1.4.4 which is in no way greater than 1.5.0, but the lib true for `updateAvailable` because `4 > 0`

**Comment by rwbutler** [comment]
Thanks for letting me know about this - I've released a fix (v1.2.2). Hopefully this should resolve the issue for you.
