### ISSUE TITLE
Displaying results when the update is less than current version

### ISSUE THREAD

**Issue by willMorph** [rwbutler/Updates#7]
Displaying results when the update is less than the current version

running 13.4.1 and it's displaying an available update of 7.51
as well tried with running version 7.51 and it's saying that there's still an update available!!

Please!!

**Comment by rwbutler** [comment]
Hi @willMorph, thanks for letting me know about this - could you tell me which version of the library you're using and whether you're integrating through Cocoapods?

**Comment by willMorph** [comment]
Sure thing, 

I am using the latest Release 1.2.2

And have installed using cocoapods.

I have configured it exactly as directed in the readme 

'''
Updates.checkForUpdates { result in
    // Implement custom UI or use UpdatesUI component
}
'''

**Comment by rwbutler** [comment]
Thanks for getting back to me so promptly! That all sounds good - if you're able to would you be able to let me know the bundle identifier of your app and which App Store it's in (US / UK etc)? I should be able to replicate the issue fairly quickly with this information. If you're not comfortable posting that here feel free to drop me an e-mail to github [at] rwbutler.com

**Comment by rwbutler** [comment]
Also could you confirm the Bundle version string (short) of your app for which an update is available?

**Comment by rwbutler** [comment]
After investigating - the issues doesn't seem to be present on the latest version 1.2.2. This was an issues in 1.2.1 but was fixed, see [changelog](https://github.com/rwbutler/Updates/blob/master/CHANGELOG.md). Therefore I'm closing this issue for now but if you are able to provide the information above / circumstances to reproduce this I'll re-open and investigate further.
