### ISSUE TITLE
NotificationMode is not respected: update UI is always shown

### ISSUE THREAD

**Issue by pwoods-al** [rwbutler/Updates#9]
**Describe the bug**
Setting the `notificationMode` via JSON or in code does not change the outcome of the call to `Updates.checkForUpdates` or the call to `UpdatesUI.promptToUpdate`. The update UI is always shown no matter what value is stored to the `notificationMode` configuration setting.

**To Reproduce**

```
Updates.updatingMode = .automatically
Updates.notifying = .once

Updates.checkForUpdates { result in
    UpdatesUI.promptToUpdate(result, presentingViewController: self)
}
```

The update prompt is shown every time the above code is called.

**Expected behavior**
User is only shown the update prompt once.

**Comment by rwbutler** [comment]
Thanks for letting me know about this - I'll investigate!

**Comment by NikitaHappilyUnmarried** [comment]
Facing the same issue, the update prompt is always shown.

**Comment by rwbutler** [comment]
@NikitaHappilyUnmarried @pwoods-al  Sorry for the delay with this - could you try v1.2.4? This issue should now be resolved thanks.
